markdown: redcarpet
permalink: /:title.html
destination: ../../public/blog
auto: true
excerpt_separator: "\n\n"
paginate: 3
paginate_path: "/page/:num"
gems: [jekyll-paginate, classifier-reborn]
keep_files: [.git]
lsi: true
encoding: UTF-8
permalink: pretty
url: gvf.co.in/blog
title: Blog@GVF
exclude:
  - Rakefile
  - Gemfile
  - .gitignore
blog_pages:       
  Archive: '/blog/archive'
  Feed: '/blog/atom.xml'
about_pages:       
  Advisory Body: '/advisorybody'
  Governing Council: '/governingcouncil'
  Directors: '/directors'
  People: '/people'
team_pages:
  Administration: '/admin'
  Agriculture, Animal Husbandry & Rural Development: '/agri'
  Beti bachao, Beti padhao (Women Empowerment): '/b3p'
  Education: '/edu'
  Energy: '/energy'
  Environment: '/env'
  Industry: '/industry'
  IT: '/it'
  Operations: '/operations'
  Public Financial Management: '/finance'
  Public Health: '/pubhealth'
  Skill Development: '/skill'
  Tourism: '/tourism'
  Urban Development: '/urbdev'